from enum import StrEnum


class UserRole(StrEnum):
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    DOCUMENT_ADMIN = "DOCUMENT_ADMIN"
    DEPARTMENT_MANAGER = "DEPARTMENT_MANAGER"
    USER = "USER"


class AuditAction(StrEnum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    TOKEN_REFRESH = "TOKEN_REFRESH"
    LOGOUT = "LOGOUT"
    USER_CREATE = "USER_CREATE"
    USER_UPDATE = "USER_UPDATE"
    USER_ACTIVATE = "USER_ACTIVATE"
    USER_DEACTIVATE = "USER_DEACTIVATE"
    USER_ROLE_CHANGE = "USER_ROLE_CHANGE"
    DEPARTMENT_CREATE = "DEPARTMENT_CREATE"
    DEPARTMENT_UPDATE = "DEPARTMENT_UPDATE"
