from enum import StrEnum


class UserRole(StrEnum):
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    DOCUMENT_ADMIN = "DOCUMENT_ADMIN"
    DEPARTMENT_MANAGER = "DEPARTMENT_MANAGER"
    USER = "USER"


class DocumentStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PROCESSING = "PROCESSING"
    FAILED = "FAILED"


class AuditAction(StrEnum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    TOKEN_REFRESH = "TOKEN_REFRESH"
    LOGOUT = "LOGOUT"
    USER_CREATE = "USER_CREATE"
    USER_UPDATE = "USER_UPDATE"
    USER_ACTIVATE = "USER_ACTIVATE"
    USER_DEACTIVATE = "USER_DEACTIVATE"
    USER_ROLE_CHANGE = "USER_ROLE_CHANGE"
    DEPARTMENT_CREATE = "DEPARTMENT_CREATE"
    DEPARTMENT_UPDATE = "DEPARTMENT_UPDATE"
    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
    DOCUMENT_LIST = "DOCUMENT_LIST"
    DOCUMENT_VIEW = "DOCUMENT_VIEW"
    DOCUMENT_DOWNLOAD = "DOCUMENT_DOWNLOAD"
    DOCUMENT_DELETE = "DOCUMENT_DELETE"
    DOCUMENT_UPLOAD_FAILED = "DOCUMENT_UPLOAD_FAILED"
    DOCUMENT_VERSION_UPLOAD = "DOCUMENT_VERSION_UPLOAD"
    DOCUMENT_VERSION_DOWNLOAD = "DOCUMENT_VERSION_DOWNLOAD"
