from fastapi import HTTPException, status


class ErrorCode:
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_INACTIVE_USER = "AUTH_INACTIVE_USER"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_EXPIRED_TOKEN = "AUTH_EXPIRED_TOKEN"
    AUTH_REFRESH_TOKEN_REQUIRED = "AUTH_REFRESH_TOKEN_REQUIRED"
    AUTH_REFRESH_TOKEN_REVOKED = "AUTH_REFRESH_TOKEN_REVOKED"
    FORBIDDEN = "FORBIDDEN"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_EMAIL_DUPLICATED = "USER_EMAIL_DUPLICATED"
    DEPARTMENT_NOT_FOUND = "DEPARTMENT_NOT_FOUND"
    DEPARTMENT_NAME_DUPLICATED = "DEPARTMENT_NAME_DUPLICATED"
    INVALID_ROLE = "INVALID_ROLE"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    DOCUMENT_ACCESS_DENIED = "DOCUMENT_ACCESS_DENIED"
    DOCUMENT_DOWNLOAD_DENIED = "DOCUMENT_DOWNLOAD_DENIED"
    DOCUMENT_INVALID_EXTENSION = "DOCUMENT_INVALID_EXTENSION"
    DOCUMENT_INVALID_MIME_TYPE = "DOCUMENT_INVALID_MIME_TYPE"
    DOCUMENT_EMPTY_FILE = "DOCUMENT_EMPTY_FILE"
    DOCUMENT_FILE_TOO_LARGE = "DOCUMENT_FILE_TOO_LARGE"
    DOCUMENT_UPLOAD_FAILED = "DOCUMENT_UPLOAD_FAILED"
    DOCUMENT_FILE_NOT_FOUND = "DOCUMENT_FILE_NOT_FOUND"
    DOCUMENT_DOWNLOAD_FAILED = "DOCUMENT_DOWNLOAD_FAILED"
    DOCUMENT_STORAGE_UNAVAILABLE = "DOCUMENT_STORAGE_UNAVAILABLE"
    DOCUMENT_ALREADY_DELETED = "DOCUMENT_ALREADY_DELETED"
    DOCUMENT_INVALID_TITLE = "DOCUMENT_INVALID_TITLE"
    DOCUMENT_VERSION_DUPLICATE = "DOCUMENT_VERSION_DUPLICATE"


def api_error(status_code: int, code: str, message: str, details: object | None = None) -> HTTPException:
    return HTTPException(status_code=status_code, detail={"error": {"code": code, "message": message, "details": details}})


def forbidden() -> HTTPException:
    return api_error(status.HTTP_403_FORBIDDEN, ErrorCode.FORBIDDEN, "접근 권한이 없습니다.")
